# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate static documentation from authoritative model verification cards."""

from __future__ import annotations

import argparse
import datetime
import html
import json
import logging
import re
import shlex
import sys
from pathlib import Path
from typing import Any

import yaml


LOGGER = logging.getLogger(__name__)
CATALOG_SCHEMA_VERSION = 1
CARD_GLOB = "examples/model_verification_cards/*/card.yaml"
GENERATED_NOTICE = "<!-- Generated by scripts/docs/generate_model_verification_catalog.py. Do not edit. -->"
NAV_START = "# BEGIN GENERATED MODEL VERIFICATION CATALOG"
NAV_END = "# END GENERATED MODEL VERIFICATION CATALOG"
MODEL_SECTION_START = "<!-- BEGIN GENERATED VERIFIED CONFIGURATIONS -->"
MODEL_SECTION_END = "<!-- END GENERATED VERIFIED CONFIGURATIONS -->"
VALID_STATUSES = {"verified", "unverified", "unsupported", "not_applicable"}
STATUS_LABELS = {
    "verified": "✅ verified",
    "unverified": "⚪ unverified",
    "unsupported": "❌ unsupported",
    "not_applicable": "➖ not applicable",
}
CAPABILITY_TABS = (
    (
        "import-export",
        "Import & Export",
        ("hf_to_megatron_cpu", "hf_to_megatron_gpu", "megatron_to_hf_cpu", "megatron_to_hf_gpu"),
    ),
    (
        "pretrain",
        "Pretrain",
        ("pretrain", "pretrain_fsdp", "pretrain_weak_scaling"),
    ),
    ("benchmark", "Benchmark", ("pretrain_performance",)),
    ("sft", "SFT", ("sft",)),
    ("lora", "LoRA", ("peft",)),
    ("long-context", "Long Context", ("sft_long_context",)),
)
PRECISION_LABELS = {
    "bf16": "BF16",
    "fp8_mx": "FP8 MX",
    "nvfp4": "NVFP4",
}
HARDWARE_ORDER = ("H100", "B200", "GB200", "GB300")
OWNER_LABELS = {
    "deepseek-ai": "DeepSeek",
    "google": "Google",
    "lgai-exaone": "LG AI EXAONE",
    "meta-models": "Meta",
    "minimaxai": "MiniMax",
    "moonshotai": "Moonshot AI",
    "nvidia": "NVIDIA",
    "openai": "OpenAI",
    "qwen": "Qwen",
    "stepfun-ai": "StepFun",
    "zai-org": "Z.ai",
}
DETECT_SECRETS_ALLOWLIST_MODEL_NAMES = frozenset(
    {
        "NVIDIA-Nemotron-3-Super-120B-A12B-BF16",
        "NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    }
)
MODEL_PAGE_PATHS = {
    "deepseek-v3": "models/deepseek/deepseek-v3.md",
    "deepseek-v4-flash": "models/deepseek/deepseek-v4.md",
    "gemma-3-4b-it": "models/gemma/gemma3-vl.md",
    "gemma-4-26b-a4b-it": "models/gemma/gemma4-vl.md",
    "glm5": "models/glm/glm5.md",
    "glm5-2": "models/glm/glm5-2.md",
    "gpt-oss-120b": "models/gpt_oss/gpt-oss-120b.md",
    "gpt-oss-20b": "models/gpt_oss/gpt-oss-20b.md",
    "k-exaone-2": "models/exaone/exaone.md",
    "kimi-k3": "models/kimi/kimi-k3.md",
    "minimax-m3": "models/minimax/minimax-m3.md",
    "moonlight-16b-a3b": "models/moonlight/moonlight.md",
    "muse-glimmer-30b": "models/muse_glimmer/muse-glimmer.md",
    "nemotron-3-nano-30b-a3b": "models/nemotron/nemotron3-nano.md",
    "nemotron-3-nano-4b": "models/nemotron/nemotron3-nano-4b.md",
    "nemotron-3-nano-omni-30b-a3b-reasoning": "models/nemotron/nemotron-3-omni.md",
    "nemotron-3-super-120b-a12b": "models/nemotron/nemotron3-super.md",
    "nemotron-3-ultra-550b-a55b": "models/nemotron/nemotron3-ultra.md",
    "nemotron-3.5-lightning": "models/nemotron/nemotron3.5-lightning.md",
    "qwen3-235b-a22b": "models/qwen/qwen3-235b-a22b.md",
    "qwen3-30b-a3b": "models/qwen/qwen3-30b-a3b.md",
    "qwen3-8b": "models/qwen/qwen3-8b.md",
    "qwen3.6-35b-a3b": "models/qwen/qwen3.6-35b-a3b.md",
    "qwen3.8-27b": "models/qwen/qwen3.8-27b.md",
    "step35-flash": "models/stepfun/step35.md",
}
MODEL_PAGE_TITLES = {
    "glm5": "GLM-5",
    "glm5-2": "GLM-5.2",
    "gpt-oss-120b": "GPT OSS 120B",
    "gpt-oss-20b": "GPT OSS 20B",
    "nemotron-3-nano-4b": "Nemotron 3 Nano 4B",
    "nemotron-3.5-lightning": "Nemotron 3.5 Lightning",
    "qwen3-235b-a22b": "Qwen3-235B-A22B",
    "qwen3-30b-a3b": "Qwen3-30B-A3B",
    "qwen3-8b": "Qwen3-8B",
    "qwen3.6-35b-a3b": "Qwen3.6-35B-A3B",
    "qwen3.8-27b": "Qwen3.8-27B",
}
MODEL_INTRO_SOURCES = {
    "glm5-2": "models/glm/glm5.md",
    "gpt-oss-120b": "models/gpt_oss/gpt-oss.md",
    "gpt-oss-20b": "models/gpt_oss/gpt-oss.md",
    "nemotron-3-nano-4b": "models/nemotron/nemotron3-nano.md",
    "nemotron-3.5-lightning": "models/nemotron/nemotron3-super.md",
    "qwen3-235b-a22b": "models/qwen/qwen.md",
    "qwen3-30b-a3b": "models/qwen/qwen.md",
    "qwen3-8b": "models/qwen/qwen.md",
    "qwen3.6-35b-a3b": "models/qwen/qwen35-vl.md",
    "qwen3.8-27b": "models/qwen/qwen35-vl.md",
}
RETIRED_COMBINED_MODEL_DOCS = (
    "models/gpt_oss/gpt-oss.md",
    "models/qwen/qwen.md",
    "models/qwen/qwen35-vl.md",
)
METRIC_PRESENTATIONS = {
    "initial_loss": ("Initial loss", ""),
    "final_loss": ("Final loss", ""),
    "last_10_steps_step_time_ms_avg": ("Step time · last 10 avg", " ms"),
    "last_10_steps_model_tflops_per_gpu_avg": ("Model throughput · last 10 avg", " TFLOP/s/GPU"),
    "last_10_steps_tokens_per_second_per_gpu_avg": ("Token throughput · last 10 avg", " tokens/s/GPU"),
    "peak_allocated_memory_gib": ("Peak allocated memory", " GiB"),
    "peak_reserved_memory_gib": ("Peak reserved memory", " GiB"),
}
TOPOLOGY_FLAGS = {
    "nodes": ("--nodes",),
    "gpus_per_node": ("--gpus-per-node", "--gpus_per_node"),
    "tensor_parallel": (
        "--tp",
        "--tensor-model-parallel-size",
        "--tensor_model_parallel_size",
        "model.tensor_model_parallel_size",
    ),
    "pipeline_parallel": (
        "--pp",
        "--pipeline-model-parallel-size",
        "--pipeline_model_parallel_size",
        "model.pipeline_model_parallel_size",
    ),
    "context_parallel": (
        "--cp",
        "--context-parallel-size",
        "--context_parallel_size",
        "model.context_parallel_size",
    ),
    "expert_parallel": (
        "--ep",
        "--expert-model-parallel-size",
        "--expert_model_parallel_size",
        "model.expert_model_parallel_size",
    ),
    "expert_tensor_parallel": (
        "--etp",
        "--expert-tensor-parallel-size",
        "--expert_tensor_parallel_size",
        "model.expert_tensor_parallel_size",
    ),
    "sequence_length": ("--seq-length", "--seq_length", "model.seq_length"),
    "recipe": ("--recipe",),
}


class CatalogError(ValueError):
    """Raised when a card cannot be normalized without inventing information."""


def _mapping(value: object, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise CatalogError(f"{context} must be a mapping")
    return value


def _text(value: object | None) -> str | None:
    if value is None:
        return None
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.isoformat()
    return str(value)


def _json_value(value: object) -> object:
    if isinstance(value, dict):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_value(item) for item in value]
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.isoformat()
    return value


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "entry"


def _commands(item: dict[str, Any], context: str) -> list[str]:
    command = item.get("command")
    commands = item.get("commands")
    if command is not None and commands is not None:
        raise CatalogError(f"{context} has both command and commands")
    if command is not None:
        return [str(command).strip()]
    if commands is None:
        return []
    if not isinstance(commands, list) or not all(isinstance(value, str) for value in commands):
        raise CatalogError(f"{context}.commands must be a list of strings")
    return [value.strip() for value in commands]


def _flag_value(tokens: list[str], aliases: tuple[str, ...]) -> str | None:
    for index, token in enumerate(tokens):
        for alias in aliases:
            if token == alias and index + 1 < len(tokens):
                return tokens[index + 1]
            if token.startswith(f"{alias}="):
                return token.split("=", 1)[1]
    return None


def command_topology(command: str) -> dict[str, object]:
    """Extract only topology values explicitly present in one command."""
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()
    topology: dict[str, object] = {}
    for name, aliases in TOPOLOGY_FLAGS.items():
        value = _flag_value(tokens, aliases)
        if value is not None:
            topology[name] = value
    nodes = topology.get("nodes")
    gpus_per_node = topology.get("gpus_per_node")
    if isinstance(nodes, str) and isinstance(gpus_per_node, str) and nodes.isdigit() and gpus_per_node.isdigit():
        topology["total_gpus"] = int(nodes) * int(gpus_per_node)
    return topology


def _entry(
    *,
    model_slug: str,
    workflow: str,
    hardware: str | None,
    variant: str | None,
    source_pointer: str,
    item: dict[str, Any],
    inherited: dict[str, Any],
    dimensions: dict[str, object] | None = None,
) -> dict[str, object]:
    merged = {**inherited, **item}
    status = _text(merged.get("status"))
    if status not in VALID_STATUSES:
        raise CatalogError(f"{source_pointer}.status must be one of {sorted(VALID_STATUSES)}")
    commands = _commands(merged, source_pointer)
    identity = [model_slug, workflow]
    if hardware:
        identity.append(hardware)
    if variant:
        identity.append(variant)
    entry_id = _slug("-".join(identity))
    return {
        "entry_id": entry_id,
        "source_pointer": source_pointer,
        "workflow": workflow,
        "hardware": hardware,
        "variant": variant,
        "status": status,
        "precision": _text(merged.get("precision")),
        "last_verified": _text(merged.get("last_verified")),
        "bridge_commit": _text(merged.get("bridge_commit")),
        "commands": commands,
        "command_topologies": [command_topology(command) for command in commands],
        "dimensions": _json_value(dimensions or {}),
        "enabled_features": _json_value(merged.get("enabled_features", {})),
        "metrics": _json_value(merged.get("metrics", {})),
        "expected_result": _text(merged.get("expected_result")),
    }


def _normal_item_entries(
    model_slug: str,
    workflow: str,
    hardware: str | None,
    source_pointer: str,
    item: dict[str, Any],
    inherited: dict[str, Any],
) -> list[dict[str, object]]:
    if "variants" in item:
        variants = _mapping(item["variants"], f"{source_pointer}.variants")
        parent = {**inherited, **{key: value for key, value in item.items() if key != "variants"}}
        return [
            _entry(
                model_slug=model_slug,
                workflow=workflow,
                hardware=hardware,
                variant=str(name),
                source_pointer=f"{source_pointer}.variants.{name}",
                item=_mapping(value, f"{source_pointer}.variants.{name}"),
                inherited=parent,
            )
            for name, value in variants.items()
        ]
    if "points" in item:
        points = item["points"]
        if not isinstance(points, list):
            raise CatalogError(f"{source_pointer}.points must be a list")
        parent = {**inherited, **{key: value for key, value in item.items() if key != "points"}}
        entries = []
        for index, point_value in enumerate(points):
            point = _mapping(point_value, f"{source_pointer}.points[{index}]")
            num_gpus = point.get("num_gpus")
            variant = f"{num_gpus}-gpu" if num_gpus is not None else f"point-{index + 1}"
            dimensions = {
                str(key): _json_value(value)
                for key, value in point.items()
                if key
                not in {
                    "status",
                    "precision",
                    "last_verified",
                    "bridge_commit",
                    "command",
                    "commands",
                    "metrics",
                    "enabled_features",
                    "expected_result",
                }
            }
            entries.append(
                _entry(
                    model_slug=model_slug,
                    workflow=workflow,
                    hardware=hardware,
                    variant=variant,
                    source_pointer=f"{source_pointer}.points[{index}]",
                    item=point,
                    inherited=parent,
                    dimensions=dimensions,
                )
            )
        return entries
    return [
        _entry(
            model_slug=model_slug,
            workflow=workflow,
            hardware=hardware,
            variant=None,
            source_pointer=source_pointer,
            item=item,
            inherited=inherited,
        )
    ]


def normalize_card(card_path: Path, repo_root: Path) -> dict[str, object]:
    """Normalize one YAML card into exact concrete configurations."""
    with card_path.open(encoding="utf-8") as stream:
        card = _mapping(yaml.safe_load(stream), str(card_path))
    model = _mapping(card.get("model"), f"{card_path}: model")
    environment = _mapping(card.get("verification_environment"), f"{card_path}: verification_environment")
    items = _mapping(card.get("items"), f"{card_path}: items")
    model_slug = card_path.parent.name
    entries: list[dict[str, object]] = []
    inherited = {"bridge_commit": environment.get("bridge_commit")}
    for workflow, raw_item in items.items():
        item = _mapping(raw_item, f"items.{workflow}")
        source_pointer = f"items.{workflow}"
        if "status" in item and any(key in item for key in ("command", "commands", "variants", "points")):
            entries.extend(_normal_item_entries(model_slug, workflow, None, source_pointer, item, inherited))
            continue
        for hardware, raw_hardware_item in item.items():
            hardware_item = _mapping(raw_hardware_item, f"{source_pointer}.{hardware}")
            entries.extend(
                _normal_item_entries(
                    model_slug,
                    workflow,
                    str(hardware),
                    f"{source_pointer}.{hardware}",
                    hardware_item,
                    inherited,
                )
            )
    pointers = [str(entry["source_pointer"]) for entry in entries]
    entry_ids = [str(entry["entry_id"]) for entry in entries]
    if len(pointers) != len(set(pointers)):
        raise CatalogError(f"{card_path} contains duplicate normalized source pointers")
    if len(entry_ids) != len(set(entry_ids)):
        raise CatalogError(f"{card_path} produces duplicate entry ids")
    return {
        "slug": model_slug,
        "title": _text(card.get("title")) or model_slug,
        "summary": _text(card.get("summary")) or "",
        "source_card": card_path.relative_to(repo_root).as_posix(),
        "hf_id": _text(model.get("hf_id")) or "",
        "hf_revision": _text(model.get("hf_revision")),
        "architecture": _text(model.get("architecture")),
        "min_transformers_version": _text(model.get("min_transformers_version")),
        "base_container": _text(environment.get("base_container")),
        "bridge_commit": _text(environment.get("bridge_commit")),
        "entries": entries,
    }


def build_catalog(repo_root: Path) -> dict[str, object]:
    """Discover all cards and build the versioned normalized catalog."""
    cards = sorted(repo_root.glob(CARD_GLOB))
    if not cards:
        raise CatalogError(f"no cards matched {CARD_GLOB}")
    models = [normalize_card(card, repo_root) for card in cards]
    models.sort(key=lambda model: (str(model["hf_id"]).casefold(), str(model["slug"])))
    return {
        "schema_version": CATALOG_SCHEMA_VERSION,
        "source": CARD_GLOB,
        "generation": "offline-derived; YAML cards remain authoritative",
        "models": models,
    }


def _md_cell(value: object | None) -> str:
    if value is None or value == "":
        return "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


def _status_label(status: str) -> str:
    return STATUS_LABELS[status]


def _model_status(entries: list[dict[str, object]]) -> str:
    statuses = {str(entry["status"]) for entry in entries}
    if statuses == {"verified"}:
        return "verified"
    if "verified" in statuses:
        return "partially verified"
    for status in ("unverified", "unsupported", "not_applicable"):
        if status in statuses:
            return status.replace("_", " ")
    raise CatalogError("model has no concrete configuration status")


def _find_model_doc(repo_root: Path, model: dict[str, object]) -> str:
    override = MODEL_PAGE_PATHS.get(str(model["slug"]))
    if override:
        return override
    needles = [str(model["source_card"]), str(model["hf_id"]), str(model["slug"])]
    candidates: list[tuple[int, int, str]] = []
    for path in sorted((repo_root / "docs/models").rglob("*.md")):
        content = path.read_text(encoding="utf-8")
        score = sum((3 - index) for index, needle in enumerate(needles) if needle and needle in content)
        if score:
            relative = path.relative_to(repo_root / "docs").as_posix()
            candidates.append((-score, len(relative), relative))
    if not candidates:
        return "models/README.md"
    return min(candidates)[2]


def _status_badge(status: str, label: str | None = None) -> str:
    presentations = {
        "verified": ("✓", "Verified"),
        "partial": ("◐", "Partial"),
        "unverified": ("○", "Unverified"),
        "unsupported": ("×", "Unsupported"),
        "not-applicable": ("—", "Not applicable"),
    }
    icon, status_label = presentations[status]
    text = f"{label} {icon}" if label else f"{icon} {status_label}"
    return (
        f'<span class="verification-status verification-status--{status}" title="{status_label}">'
        f"{html.escape(text)}</span>"
    )


def _directory_status(entries: list[dict[str, object]]) -> str:
    model_status = _model_status(entries)
    if model_status == "partially verified":
        return "partial"
    return model_status.replace("_", "-").replace(" ", "-")


def _model_directory(catalog: dict[str, object], repo_root: Path, *, fern: bool) -> list[str]:
    providers: dict[str, list[dict[str, object]]] = {}
    for raw_model in catalog["models"]:
        model = _mapping(raw_model, "catalog model")
        owner = str(model["hf_id"]).partition("/")[0]
        providers.setdefault(owner, []).append(model)
    lines = [
        "## Models",
        "",
        "Choose a model to inspect its recorded import/export, training, and precision combinations.",
        "",
        '<div class="verification-provider-grid verification-model-directory">',
    ]
    for owner, models in providers.items():
        owner_label = OWNER_LABELS.get(owner.casefold(), owner)
        lines.extend(
            [
                '  <section class="verification-provider-card">',
                '    <header class="verification-provider-heading">',
                f"      <strong>{html.escape(owner_label)}</strong>",
                f"      <span>{len(models)} model{'s' if len(models) != 1 else ''}</span>",
                "    </header>",
                '    <div class="verification-provider-models">',
            ]
        )
        for model in models:
            hf_id = str(model["hf_id"])
            _, separator, model_name = hf_id.partition("/")
            if not separator:
                model_name = hf_id
            model_doc = _find_model_doc(repo_root, model)
            suffix = "" if fern else ".html"
            relative_model_doc = model_doc.removeprefix("models/").removesuffix(".md")
            href = f"{relative_model_doc}{suffix}#verified-{model['slug']}"
            entries = [_mapping(entry, f"{model['slug']} entry") for entry in model["entries"]]
            status = _directory_status(entries)
            allowlist_suffix = (
                " <!-- pragma: allowlist secret -->" if model_name in DETECT_SECRETS_ALLOWLIST_MODEL_NAMES else ""
            )
            lines.extend(
                [
                    f'      <a class="verification-model-link" href="{href}">',
                    f'        <strong title="{html.escape(hf_id, quote=True)}">{html.escape(model_name)}</strong>'
                    f"{allowlist_suffix}",
                    f"        {_status_badge(status)}",
                    "      </a>",
                ]
            )
        lines.extend(["    </div>", "  </section>"])
    lines.extend(["</div>", ""])
    return lines


def _entry_capability(entry: dict[str, object]) -> tuple[str, str] | None:
    workflow = str(entry["workflow"])
    for capability_id, capability_label, workflows in CAPABILITY_TABS:
        if workflow in workflows:
            return capability_id, capability_label
    return None


def _entry_option_label(entry: dict[str, object]) -> str:
    workflow_labels = {
        "hf_to_megatron_cpu": "Import · CPU",
        "hf_to_megatron_gpu": "Import · GPU",
        "megatron_to_hf_cpu": "Export · CPU",
        "megatron_to_hf_gpu": "Export · GPU",
        "pretrain": "Pretrain",
        "pretrain_fsdp": "Pretrain · FSDP",
        "pretrain_performance": "Benchmark",
        "pretrain_weak_scaling": "Pretrain · Weak scaling",
        "sft": "SFT",
        "peft": "LoRA",
        "sft_long_context": "Long Context",
    }
    parts = [workflow_labels[str(entry["workflow"])]]
    if entry.get("hardware") and entry["hardware"] != "all":
        parts.append(str(entry["hardware"]))
    if entry.get("variant"):
        parts.append(str(entry["variant"]))
    return " · ".join(parts)


def _model_combination_button(entry: dict[str, object]) -> list[str]:
    capability = _entry_capability(entry)
    if capability is None:
        return []
    capability_id, _ = capability
    precision = str(entry.get("precision") or "")
    hardware = str(entry.get("hardware") or "")
    if hardware == "all":
        hardware = ""
    precision_label = PRECISION_LABELS.get(precision, precision.upper()) if precision else "Precision not specified"
    status = str(entry["status"]).replace("_", "-")
    label = _entry_option_label(entry)
    return [
        f'<button type="button" class="verification-combination" data-capability="{capability_id}" '
        f'data-precision="{html.escape(precision, quote=True)}" '
        f'data-hardware="{html.escape(hardware, quote=True)}" data-status="{status}" '
        f'data-entry="{entry["entry_id"]}" '
        f'aria-controls="{entry["entry_id"]}" aria-pressed="false">',
        '  <span class="verification-combination-heading">',
        f"    <strong>{html.escape(label)}</strong>",
        f"    {_status_badge(status)}",
        "  </span>",
        f'  <span class="verification-combination-meta">{html.escape(precision_label)}</span>',
        "</button>",
    ]


def _format_metric_value(key: str, value: object, suffix: str) -> str:
    if isinstance(value, float):
        formatted = f"{value:.8g}" if key in {"initial_loss", "final_loss"} else f"{value:,.3f}"
    else:
        formatted = str(value)
    return formatted + suffix


def _recorded_metrics(entry: dict[str, object], *, heading_level: int) -> list[str]:
    metrics = _mapping(entry.get("metrics", {}), "entry metrics")
    presented = [
        (label, _format_metric_value(key, metrics[key], suffix))
        for key, (label, suffix) in METRIC_PRESENTATIONS.items()
        if key in metrics
    ]
    if not presented:
        return []
    lines = [
        '  <section class="verification-recorded-metrics">',
        f"    <h{heading_level}>Recorded metrics</h{heading_level}>",
        '    <dl class="verification-metric-list">',
    ]
    for label, value in presented:
        lines.extend(
            [
                "      <div>",
                f"        <dt>{html.escape(label)}</dt>",
                f"        <dd>{html.escape(value)}</dd>",
                "      </div>",
            ]
        )
    lines.extend(["    </dl>", "  </section>"])
    return lines


def _model_combination_detail(entry: dict[str, object], *, heading_level: int) -> list[str]:
    status = str(entry["status"]).replace("_", "-")
    precision = str(entry.get("precision") or "not specified")
    precision_label = PRECISION_LABELS.get(precision, precision.upper())
    commands = entry["commands"]
    subsection_level = min(heading_level + 1, 6)
    lines = [
        f'<article id="{entry["entry_id"]}" class="verification-model-detail" '
        f'data-entry-detail="{entry["entry_id"]}" tabindex="-1">',
        '  <header class="verification-model-detail-heading">',
        f"    <h{heading_level}>{html.escape(_entry_option_label(entry))}</h{heading_level}>",
        f"    {_status_badge(status)}",
        "  </header>",
        '  <dl class="verification-model-detail-meta">',
        f"    <div><dt>Hardware</dt><dd>{html.escape(str(entry.get('hardware') or 'not specified'))}</dd></div>",
        f"    <div><dt>Precision</dt><dd>{html.escape(precision_label)}</dd></div>",
        f"    <div><dt>Last verified</dt><dd>{html.escape(str(entry.get('last_verified') or '—'))}</dd></div>",
        "  </dl>",
    ]
    lines.extend(_recorded_metrics(entry, heading_level=subsection_level))
    lines.extend(
        [
            '  <section class="verification-command-section">',
            f"    <h{subsection_level}>Exact command</h{subsection_level}>",
        ]
    )
    if isinstance(commands, list) and commands:
        for index, command in enumerate(commands, start=1):
            command_label = f"Command {index}" if len(commands) > 1 else "Command"
            lines.extend(
                [
                    '    <div class="verification-command">',
                    '      <div class="verification-command-heading">',
                    f"        <span>{command_label}</span>",
                    '        <button type="button" class="verification-copy-command">Copy</button>',
                    "      </div>",
                    f'      <pre><code class="language-bash">{html.escape(str(command))}</code></pre>',
                    "    </div>",
                ]
            )
    else:
        lines.append("    <p>No runnable command is recorded for this status.</p>")
    expected_result = str(entry.get("expected_result") or "None recorded.")
    lines.extend(
        [
            "  </section>",
            '  <section class="verification-expected-result">',
            f"    <h{subsection_level}>Expected result</h{subsection_level}>",
            f"    <p>{html.escape(expected_result)}</p>",
            "  </section>",
            "</article>",
        ]
    )
    return lines


def _model_explorer(entries: list[dict[str, object]], *, heading_level: int = 2) -> list[str]:
    focused_entries = [entry for entry in entries if _entry_capability(entry) is not None]
    lines = [
        f"{'#' * heading_level} Run a configuration",
        "",
        "Choose a workflow, precision, and exact recorded combination. The command and expected result update below.",
        "",
        '<div class="verification-model-explorer" data-model-explorer>',
        '  <div class="verification-model-controls" hidden>',
        '    <div class="verification-capability-tabs" role="tablist" aria-label="Workflow">',
    ]
    available_capabilities = {
        capability[0] for entry in focused_entries if (capability := _entry_capability(entry)) is not None
    }
    hardware_order = {hardware: index for index, hardware in enumerate(HARDWARE_ORDER)}
    hardware_values = sorted(
        {str(entry["hardware"]) for entry in focused_entries if entry.get("hardware") not in (None, "all")},
        key=lambda hardware: (hardware_order.get(hardware, len(hardware_order)), hardware),
    )
    for index, (capability_id, label, _) in enumerate(CAPABILITY_TABS):
        selected = "true" if index == 0 else "false"
        disabled = " disabled" if capability_id not in available_capabilities else ""
        lines.append(
            f'      <button type="button" role="tab" aria-selected="{selected}" '
            f'data-capability-tab="{capability_id}"{disabled}>{label}</button>'
        )
    lines.extend(
        [
            "    </div>",
            '    <div class="verification-filter-row">',
            '      <div class="verification-precision-controls" aria-label="Precision filter">',
            "        <span>Precision</span>",
            '        <button type="button" class="is-active" data-precision="">All</button>',
        ]
    )
    for precision, label in PRECISION_LABELS.items():
        lines.append(f'        <button type="button" data-precision="{precision}">{label}</button>')
    lines.extend(
        [
            "      </div>",
            '      <div class="verification-hardware-controls" aria-label="GPU filter">',
            "        <span>GPU</span>",
            '        <button type="button" class="is-active" data-hardware="">All</button>',
        ]
    )
    for hardware in hardware_values:
        lines.append(
            f'        <button type="button" data-hardware="{html.escape(hardware)}">{html.escape(hardware)}</button>'
        )
    lines.extend(
        [
            "      </div>",
            '      <span class="verification-combination-count" aria-live="polite"></span>',
            "    </div>",
            "  </div>",
            '  <div class="verification-combination-list" hidden>',
        ]
    )
    for entry in focused_entries:
        lines.extend("    " + line for line in _model_combination_button(entry))
    lines.extend(["  </div>", '  <div class="verification-model-details">'])
    for entry in focused_entries:
        lines.extend("    " + line for line in _model_combination_detail(entry, heading_level=heading_level + 1))
    lines.extend(["  </div>", "</div>", ""])
    return lines


def render_supported_models_page(catalog: dict[str, object], repo_root: Path, *, fern: bool) -> str:
    """Render the generated Supported Models directory for Sphinx or Fern."""
    models = [_mapping(model, "catalog model") for model in catalog["models"]]
    entry_count = sum(len(model["entries"]) for model in models)
    lines = [
        GENERATED_NOTICE,
        "",
        "# Supported Models",
        "",
        "Choose a model to open its interactive import/export and training configurations. "
        "Every option comes directly from an authoritative YAML verification card; independent fields "
        "are never combined into synthetic commands.",
        "",
        f"Current inventory: **{len(models)} model cards** and **{entry_count} concrete configurations**.",
        "",
        "Each model page lets you select import/export, pretraining, benchmarking, SFT, LoRA, or long-context "
        "SFT and immediately see the exact command and expected result for the recorded precision and GPU.",
        "",
    ]
    lines.extend(_model_directory(catalog, repo_root, fern=fern))
    lines.extend(
        [
            "## Verification status",
            "",
            "Statuses are explicit: ✅ **verified**, ⚪ **unverified**, ❌ **unsupported**, and "
            "➖ **not applicable**. A model page may summarize mixed concrete states as partially verified.",
            "",
            "A partially verified model contains a mix of verified and pending or unsupported configurations. "
            "Selectors expose only exact card leaves and never fabricate combinations.",
            "",
        ]
    )
    if fern:
        lines.extend(
            [
                "Fern displays the command and expected-result cards as a static fallback when interactive "
                "JavaScript is unavailable.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "The versioned normalized data is available as "
                "[`catalog-v1.json`](../_static/model-verification/catalog-v1.json).",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_model_section(models: list[dict[str, object]]) -> str:
    """Render generated verification selectors for one canonical model guide."""
    lines = [
        MODEL_SECTION_START,
        "",
        "## Verified configurations",
        "",
        "Choose an exact recorded configuration to see its command and expected result. These selectors are "
        "generated from the authoritative verification cards and never synthesize combinations.",
    ]
    multiple_models = len(models) > 1
    for model in models:
        entries = [_mapping(entry, "model entry") for entry in model["entries"]]
        lines.extend(["", f'<a id="verified-{model["slug"]}"></a>'])
        if multiple_models:
            hf_id = str(model["hf_id"])
            model_label = hf_id.partition("/")[2] or hf_id
            lines.extend([f"### {_md_cell(model_label)}", ""])
        lines.extend(_model_explorer(entries, heading_level=4 if multiple_models else 3))
    lines.extend([MODEL_SECTION_END, ""])
    return "\n".join(lines).rstrip() + "\n"


def _merge_model_page(content: str, section: str, *, title: str | None = None) -> str:
    """Keep the original page introduction and replace its remaining sections."""
    has_start = MODEL_SECTION_START in content
    has_end = MODEL_SECTION_END in content
    if has_start != has_end:
        raise CatalogError("canonical model guide has an incomplete generated verification block")
    if has_start:
        introduction = content.partition(MODEL_SECTION_START)[0].rstrip()
    else:
        first_section = re.search(r"^## .+$", content, re.MULTILINE)
        introduction = content[: first_section.start()].rstrip() if first_section else content.rstrip()
    introduction = "\n".join(line.rstrip() for line in introduction.splitlines())
    introduction = re.sub(r"\[([^\]]+)\]\(#[^)]+\)", r"\1", introduction)
    if not re.search(r"^# .+$", introduction, re.MULTILINE):
        raise CatalogError("canonical model guide must have a level-one title")
    if title is not None:
        introduction = re.sub(r"^# .+$", f"# {title}", introduction, count=1, flags=re.MULTILINE)
    return f"{introduction}\n\n{section.rstrip()}\n"


def _render_nav_section() -> str:
    return ""


def _update_nav(nav_text: str) -> str:
    has_start = NAV_START in nav_text
    has_end = NAV_END in nav_text
    if has_start != has_end:
        raise CatalogError("Fern navigation has an incomplete generated model verification block")
    if not has_start:
        return nav_text
    pattern = re.compile(rf"{re.escape(NAV_START)}.*?{re.escape(NAV_END)}\n?", re.DOTALL)
    return pattern.sub(_render_nav_section(), nav_text)


def expected_outputs(repo_root: Path, catalog: dict[str, object]) -> dict[Path, str]:
    """Return every generated artifact and its deterministic content."""
    outputs = {
        repo_root / "docs/models/README.md": render_supported_models_page(catalog, repo_root, fern=False),
        repo_root / "docs/fern/versions/nightly/pages/models/README.mdx": render_supported_models_page(
            catalog, repo_root, fern=True
        ),
        repo_root / "docs/_static/model-verification/catalog-v1.json": json.dumps(catalog, indent=2, sort_keys=True)
        + "\n",
    }
    canonical_groups: dict[str, list[dict[str, object]]] = {}
    for raw_model in catalog["models"]:
        model = _mapping(raw_model, "catalog model")
        canonical_groups.setdefault(_find_model_doc(repo_root, model), []).append(model)
    for model_doc, models in canonical_groups.items():
        section = render_model_section(models)
        sphinx_path = repo_root / "docs" / model_doc
        fern_relative = Path(model_doc).with_suffix(".mdx")
        fern_path = repo_root / "docs/fern/versions/nightly/pages" / fern_relative
        if len(models) != 1:
            raise CatalogError(f"canonical model guide must map to exactly one card: {model_doc}")
        model = models[0]
        source_path = sphinx_path
        if not source_path.is_file():
            intro_source = MODEL_INTRO_SOURCES.get(str(model["slug"]))
            if intro_source is None:
                raise CatalogError(f"canonical model guide is missing for {model_doc}")
            source_path = repo_root / "docs" / intro_source
        title = MODEL_PAGE_TITLES.get(str(model["slug"]))
        merged_page = _merge_model_page(source_path.read_text(encoding="utf-8"), section, title=title)
        outputs[sphinx_path] = merged_page
        outputs[fern_path] = merged_page
    nav_path = repo_root / "docs/fern/versions/nightly.yml"
    outputs[nav_path] = _update_nav(nav_path.read_text(encoding="utf-8"))
    return outputs


def generate(repo_root: Path, *, check: bool) -> bool:
    """Write generated outputs, or return whether checked-in outputs match."""
    catalog = build_catalog(repo_root)
    outputs = expected_outputs(repo_root, catalog)
    mismatches: list[str] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path.relative_to(repo_root).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    for pattern in (
        "docs/model-verification/index.md",
        "docs/model-verification/models/*.md",
        "docs/fern/versions/nightly/pages/model-verification/index.mdx",
        "docs/fern/versions/nightly/pages/model-verification/models/*.mdx",
    ):
        for path in repo_root.glob(pattern):
            if check:
                mismatches.append(path.relative_to(repo_root).as_posix())
            elif path.read_text(encoding="utf-8").startswith(GENERATED_NOTICE):
                path.unlink()
    for retired_doc in RETIRED_COMBINED_MODEL_DOCS:
        for relative_path in (Path("docs") / retired_doc, Path("docs/fern/versions/nightly/pages") / retired_doc):
            path = repo_root / relative_path.with_suffix(".mdx" if "fern" in relative_path.parts else ".md")
            if not path.exists():
                continue
            if check:
                mismatches.append(path.relative_to(repo_root).as_posix())
            else:
                path.unlink()
    if mismatches:
        LOGGER.error("generated model verification files are stale: %s", ", ".join(sorted(mismatches)))
        return False
    if not check:
        LOGGER.info(
            "updated %d canonical model guides with %d concrete entries",
            len({_find_model_doc(repo_root, _mapping(model, "model")) for model in catalog["models"]}),
            sum(len(_mapping(model, "model")["entries"]) for model in catalog["models"]),
        )
    return True


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Megatron Bridge repository root",
    )
    parser.add_argument("--check", action="store_true", help="fail when checked-in generated files are stale")
    return parser.parse_args()


def main() -> int:
    """Run the catalog generator command-line interface."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = _parse_args()
    try:
        return 0 if generate(args.repo_root.resolve(), check=args.check) else 1
    except (CatalogError, OSError, yaml.YAMLError) as error:
        LOGGER.error("%s", error)
        return 1


if __name__ == "__main__":
    sys.exit(main())
